### ISSUE TITLE
TypeError: this._resolveReqs is not a function

### ISSUE THREAD

**Issue by ptsurko** [Diokuz/puppeteer-request-mocker#14]
Getting following exception:

``` javascript
TypeError: this._resolveReqs is not a function

      at Object._onReqsCompleted (../node_modules/puppeteer-request-mocker/lib/mocker.js:138:36)
      at interceptedResponse.text.then.catch.then (../node_modules/puppeteer-request-mocker/lib/handleResponse.js:97:18)
```

Page just make fetch POST to resource and renders list of posts

My test:
```javascript
const mocker = require('puppeteer-request-mocker');
const { PendingXHR } = require('pending-xhr-puppeteer');

describe('app', () => {
  it('should display My Blog logo', async () => {
    page = await browser.newPage();
    const pendingXHR = new PendingXHR(page);

    await page.goto('http://localhost:3000', {waitUntil: 'domcontentloaded'})
    await mocker.start({
      page,
      mockList: ['https://jsonplaceholder.typicode.com/posts'],
    });
    
    await pendingXHR.waitForAllXhrFinished();
    await page.waitForSelector('section');

    const sectionCount = await page.evaluate(() => document.querySelectorAll('section').length);
    console.log('sectionCount: ', sectionCount);
    await expect(sectionCount).toBe(100);
    await expect(page).toMatch('My Blog');

    await mocker.stop();
  })
});
```

**Comment by Diokuz** [comment]
Hey, I just got the same Error, finally)
